### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by shawninder** [vigour-io/network#1]
Elaborate API, which should allow listening for connectivity changes (wifi/3g/4g/none)

**Comment by ninjatux** [comment]
## Network Plugin Specs

This plugin will inform about connectivity changes using an Observable.

#### Properties

###### `connectivity`

This property will be filled with the current type of connectivity of the device and must be an observable in order to fire events when its value changes.

**Comment by ninjatux** [comment]
@marcusbesjes can you review this?
